<?php

    global $login;

    if ($login->isUserLogged()) {
        if ($login->getRole() == 2) {

?>
    <section class="position-relative py-4 py-xl-5" style="background: var(--bs-warning-bg-subtle);">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>Správa článků na zrecenzování</h2>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="card" id="TableSorterCard">
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table table-striped table tablesorter" id="ipi-table">
                                <thead class="thead-dark">
                                    <tr>
                                        <th class="text-center">Název článku</th>
                                        <th class="text-center">autor/autoři</th>
                                        <th class="text-center">odkaz na článek</th>
                                        <th class="text-center filter-false sorter-false" style="width: 369.484px;">hodnocení (0 až 10)</th>
                                        <th class="text-center filter-false sorter-false" style="width: 247.484px;">odeslání</th>
                                    </tr>
                                </thead>
                                <tbody class="text-center">
                                    <?php
                                        if (isset($tplData)) {
                                            foreach($tplData as $vnitrniPole) {
                                                foreach($vnitrniPole as $clanek) {
                                    ?>
                                    <tr>
                                        <td><?= $clanek["nazev_clanku"]?></td>
                                        <td><?= $clanek["autori"]?></td>
                                        <td class="text-center align-middle" style="max-height: 60px;height: 60px;">
                                            <a href="NahraneClanky/<?= $clanek["odkaz"]?>">
                                                <button class="btn btn-primary border rounded-pill" type="button">
                                                    Odkaz na článek
                                                </button>
                                            </a>
                                        </td>
                                        <td class="text-center align-middle" style="max-height: 60px;height: 60px;"><input type="number" min="0" max="10"></td>
                                        <td class="text-center align-middle" style="max-height: 60px;height: 60px;"><button class="btn btn-outline-primary" type="submit" style="border-color: var(--bs-danger-text-emphasis);color: var(--bs-danger-text-emphasis);">Odeslat</button></td>
                                    </tr>
                                                <?php
                                                }
                                            }
                                        }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        }
    }
        ?>
